services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: error_logs
      POSTGRES_USER: error_logs_user
      POSTGRES_PASSWORD: error_logs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U error_logs_user -d error_logs"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://error_logs_user:error_logs_password@postgres:5432/error_logs?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - PORT=8080
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]

volumes:
  postgres_data:
  redis_data:
